# 系统信息
server:
  port: 80	
  
spring:
  datasource:
    name: tc
    url: jdbc:mysql://127.0.0.1:3306/tc
    username: root
    password: xiaofanzhuo2019
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml    